disabled_rules:
#    - trailing_newline
#    - opening_brace
#    - empty_count
#    - comma
#    - colon
#    - force_cast
#    - type_name
#    - variable_name_min_length
#    - trailing_semicolon
#    - force_try
#    - function_body_length
#    - nesting
#    - variable_name
#    - conditional_binding_cascade
#    - variable_name_max_length
#    - operator_whitespace
#    - control_statement
#    - legacy_constant
#    - line_length
#    - return_arrow_whitespace
     - trailing_whitespace
#    - closing_brace
#    - statement_position
#    - type_body_length
#    - todo
#    - legacy_constructor
#    - valid_docs
#    - missing_docs
     - file_length
     - leading_whitespace
included: # paths to include during linting. `--path` is ignored if present.
  - ClimaX
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ClimaX/Utils
  - ClimaX/Extensions
  - ClimaX/AppDelegate.swift
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 20
type_name:
  allowed_symbols: "_"
  min_length: 3
  max_length: 60
# identifier_name:
#   allowed_symbols: "_"
#   min_length: 3
#   max_length:
#     warning: 40
#     error: 1000